### PR TITLE
fix: synchronize remote debugging plugins across cluster nodes

### LINKED ISSUE #588: remote debug return no node available
**Self Checks**

To make sure we get to you in time, please check the following :)
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify-plugin-daemon/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] "Please do not modify this template :) and fill in all the required fields."

**Versions**
1. dify-plugin-daemon Version
2. dify-api 1.11.4

**Describe the bug**
remote debug return no node available

Image

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by fatelei**
fix #588 #590 https://github.com/langgenius/dify/issues/31684

## Problem
Remote debugging plugins were not being synchronized across cluster nodes, causing "no plugin available nodes found" errors when trying to invoke plugins from different nodes.

## Root Causes
1. **Remote debugging plugins not registered to cluster** - The `ClusterTunnel` notifier was not being added to ControlPanel
2. **Plugin ID inconsistency** - Remote plugins used different plugin_id formats during installation vs. querying
3. **Non-idempotent registration** - `RegisterPlugin` failed on reconnection with "plugin has been registered" error

### Core Fixes
- **internal/types/models/curd/atomic.go**:
  - Unify plugin_id calculation for remote plugins (author/name without version)
  - Remove plugin_id from plugin query conditions
  - Clear old cache when plugin_id is updated

- **internal/cluster/plugin.go**:
  - Make `RegisterPlugin` idempotent by updating existing plugin instead of returning error

- **internal/core/control_panel/daemon.go**:
  - Add cluster field to ControlPanel
  - Add SetCluster() method for lazy cluster initialization

- **internal/core/control_panel/server_debugger.go**:
  - Register remote debugging plugins to cluster on connection
  - Unregister from cluster on disconnection

- **internal/core/plugin_manager/manager.go**:
  - Add SetCluster() method to set cluster after initialization

- **internal/server/server.go**:
  - Call SetCluster() instead of AddClusterTunnel()

### Design Decision
Only remote debugging plugins are synchronized across cluster nodes. Local plugins run only on the node where they are installed and are not registered to the cluster.

### Additional Improvements
- Error handling improvements using `errors.Is()` instead of `==`
- Handle 404 for missing plugin assets gracefully
- Handle already-installed debugging plugins gracefully

## Testing
- Remote debugging plugin can be invoked from any node in the cluster
- Plugin reconnection works without errors
- Cache invalidation works correctly when plugin_id changes

## Description

Please provide a brief description of the changes made in this pull request.
Please also include the issue number if this is related to an issue using the format `Fixes #123` or `Closes #123`.

## Type of Change

- [x] Bug fix
- [x] New feature
- [x] Refactor
- [ ] Performance improvement
- [ ] Other

### Testing
- [x] I have tested the changes locally and confirmed they work as expected
- [x] I have added unit tests where necessary and they pass successfully

### Bug Fix (if applicable)
- [x] I have used GitHub syntax to close the related issue (e.g., `Fixes #123` or `Closes #123`)

## Additional Information

Please provide any additional context that would help reviewers understand the changes.

### CODE REVIEW

File: internal/server/controllers/plugins.go [hunk 1]
```diff
@@ -18,6 +18,9 @@ func GetAsset(c *gin.Context) {
 	asset, err := pluginManager.GetAsset(c.Param("id"))
 
 	if err != nil {
+		if strings.Contains(err.Error(), "no such file or directory") {
```
Comment (Stream29) [inline internal/server/controllers/plugins.go:21]: I wonder is it good to ignore error by it's error message. Hard-coding such strings is a bad practice.

File: internal/cluster/plugin.go [hunk 2]
```diff
@@ -37,7 +37,17 @@ func (c *Cluster) RegisterPlugin(lifetime plugin_entities.PluginLifetime) error
...
+		if existing, ok := c.plugins.Load(identity.String()); ok {
+			// update the lifetime reference
+			existing.lifetime = lifetime
+			// update plugin state immediately
+			err = c.doPluginStateUpdate(existing)
+			if err != nil {
+				return errors.Join(err, errors.New("failed to update plugin state"))
+			}
+		}
+		return nil
```
Comment (Stream29) [inline internal/cluster/plugin.go:52]: At least, we should do something when not ok.

File: internal/cluster/plugin_test.go [hunk 3]
```diff
@@ -140,6 +140,107 @@ func TestPluginScheduleLifetime(t *testing.T) {
...
+		return
+	}
+
+	if len(nodes) != 1 {
+		t.Errorf("plugin not available after re-registration")
+		return
+	}
+}
+
 // TODO: I need to implement this test, now it's randomly working
```
Comment (Stream29) [inline internal/cluster/plugin_test.go]: ??? Randomly working means it's not fixed.

File: internal/server/controllers/plugins.go [hunk 4]
```diff
@@ -18,6 +18,9 @@ func GetAsset(c *gin.Context) {
...
+			return
```
Comment (Stream29) [inline internal/server/controllers/plugins.go:22]: We shouldn't return without giving any response to the request.

File: internal/types/models/curd/atomic.go [hunk 5]
```diff
@@ -68,12 +79,26 @@ func InstallPlugin(
 		} else if err != nil {
 			return err
 		} else {
+			// Update plugin_id if it differs (e.g., for remote plugins)
+			oldPluginID := p.PluginID
+			if p.PluginID != pluginID {
+				log.Info("Updating plugin_id", "from", p.PluginID, "to", pluginID)
+				p.PluginID = pluginID
+			}
```
Comment (Stream29) [inline internal/types/models/curd/atomic.go:87]: These behaviors should be tested: original bahavior with normal plugins should keep the same and debugging plugins should be installed correctly, having correct database records, even with debugging plugin reconnect.

File: internal/types/models/curd/atomic.go [hunk 6]
```diff
@@ -244,28 +281,23 @@ func UninstallPlugin(
...
+			return installation.PluginID
 		}
 
 		// delete tool installation
 		if declaration.Tool != nil {
 			toolInstallation := &models.ToolInstallation{
-				PluginID: pluginToBeReturns.PluginID,
+				PluginID: getPluginID(),
 				TenantID: tenantId,
 			}
```
Comment (Stream29) [inline internal/types/models/curd/atomic.go:302]: Similarly, these behaviors should be tested: correct both for normal plugins and debugging plugins

**Review by Stream29 — CHANGES_REQUESTED** [review]

File: internal/server/controllers/plugins.go (hunk 1 above)
Comment (fatelei) [reply internal/server/controllers/plugins.go:21]: because when no asset it will failed

**Comment by Stream29** [comment]
You can re-request a review if you think it's ready.
